#!/usr/bin/env python3.6
#
# This file is part of raind.
#
# raind is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# raind is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with raind.  If not, see <http://www.gnu.org/licenses/>.

"""Rain detector daemon for the Warwick one-metre telescope"""

# pylint: disable=broad-except
# pylint: disable=invalid-name

import datetime
import re
import threading
import time
import Pyro4
import serial
from warwick.observatory.common import daemons, log

# Set automatically when generating RPM package
SOFTWARE_VERSION = " (git-72f2534)"

SERIAL_PORT = '/dev/raindetector'
SERIAL_BAUD = 9600
SERIAL_TIMEOUT = 5

# pylint: disable=anomalous-backslash-in-string
DATA_REGEX = b'^\$(?P<port1>.)(?P<port2>.)\r\n$'
# pylint: enable=anomalous-backslash-in-string

class RainDaemon:
    """Daemon class that wraps the RS232 interface"""
    def __init__(self):
        self._lock = threading.Lock()
        self._running = True
        self._port_error = False
        self._regex = re.compile(DATA_REGEX, re.DOTALL)
        self._latest = None
        self._port = None

        runloop = threading.Thread(target=self.run)
        runloop.daemon = True
        runloop.start()

    def run(self):
        """Main run loop"""
        while self._running:
            # Initial setup
            try:
                self._port = serial.Serial(SERIAL_PORT, SERIAL_BAUD, timeout=SERIAL_TIMEOUT)
                print('Connected to', SERIAL_PORT)
                prefix = 'Restored' if self._port_error else 'Established'
                log.info('raind', prefix + ' serial connection to rain detector')
                self._port_error = False
            except Exception as exception:
                print(exception)
                print('Will retry in 10 seconds...')
                if not self._port_error:
                    log.error('vaisalad', 'Failed to connect to rain detector')

                self._port_error = True

                time.sleep(10.)
                continue

            try:
                self._latest = None

                # Flush any stale state
                self._port.flushInput()
                self._port.flushOutput()

                # First line may have been only partially recieved
                self._port.readline()

                # Main run loop
                while self._running:
                    data = self._port.readline()
                    match = self._regex.match(data)

                    if match:
                        # Port 2 is currently unused, so we ignore it
                        # Have hacked in the new sensor to channel 1
                        # Other channels are disconnected, so ignore them
                        port1 = int.from_bytes(match.group('port1'), byteorder='big')
                        unsafe_boards = 1 if port1 & 0x1 == 0x1 else 0
                        total_boards = 1
                        latest = {
                            'date': datetime.datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ'),
                            'software_version': SOFTWARE_VERSION,
                            'unsafe_boards': unsafe_boards,
                            'total_boards': total_boards,
                            'port1': port1,
                        }

                        with self._lock:
                            self._latest = latest

            except Exception as exception:
                self._port.close()
                print(exception)
                print('Will retry in 10 seconds...')
                if not self._port_error:
                    log.error('raind', 'Lost serial connection to rain board')
                self._port_error = True
                time.sleep(10.)

    @Pyro4.expose
    def last_measurement(self):
        """Query the latest valid measurement."""
        with self._lock:
            return self._latest

if __name__ == '__main__':
    daemons.onemetre_rain.launch(RainDaemon())
