#!/usr/bin/env python3.6
#
# This file is part of raind.
#
# raind is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# raind is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with raind.  If not, see <http://www.gnu.org/licenses/>.

"""Rain detector daemon for the Warwick one-metre telescope"""

# pylint: disable=broad-except
# pylint: disable=invalid-name

import datetime
import Pyro4
import RPi.GPIO as GPIO
from warwick.observatory.common import daemons

CHANNEL_PIN_TYPE = GPIO.BCM
CHANNEL_PINS = [19, 20, 21]

class RainDaemon:
    """Daemon class that wraps the RS232 interface"""
    def __init__(self):
        GPIO.setwarnings(False)
        GPIO.setmode(CHANNEL_PIN_TYPE)
        GPIO.setup(CHANNEL_PINS, GPIO.IN, pull_up_down=GPIO.PUD_UP)

    @Pyro4.expose
    def last_measurement(self):
        """Query the latest valid measurement."""
        total_boards = len(CHANNEL_PINS)
        unsafe_boards = 0
        port1 = 0
        for i, pin in enumerate(CHANNEL_PINS):
            unsafe = GPIO.input(pin) == GPIO.HIGH
            port1 |= unsafe << i
            unsafe_boards += unsafe

        return {
            'date': datetime.datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ'),
            'unsafe_boards': unsafe_boards,
            'total_boards': total_boards,
            'port1': port1
        }


if __name__ == '__main__':
    daemons.onemetre_rain.launch(RainDaemon())
